spring.application.name=Kdemy
spring.datasource.url=jdbc:postgresql://localhost:5432/kdemydb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secretKey = qwert12345qwertsdlfiwoeruweoijfdsfjlsdj
logging.level.org.springframework.security=DEBUG

file.upload-dir= uploads/videos
razorpay.key-id= rzp_test_xxxxx
razorpay.key-secret= xxxxx

