spring.application.name=Kdemy
spring.datasource.url=jdbc:postgresql://localhost:5432/kdemydb
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secretKey = qwert12345qwertsdlfiwoeruweoijfdsfjlsdj
logging.level.org.springframework.security=DEBUG

file.upload-dir= uploads/videos
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.port=8080
app.base-url=http://localhost:8080
<<<<<<< HEAD
razorpay.key-id= rzp_test_123456677
razorpay.key-secret= 123456677
=======
razorpay.key-id= rzp_test_xxxxx
razorpay.key-secret= xxxxx
>>>>>>> c85368aab4ccea7364855d8cb229bc169ca3ef19

